# Generated by Django 4.2.6 on 2023-10-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=250, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=20, verbose_name='username'),
        ),
    ]
