# Generated by Django 4.2.6 on 2023-10-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translateapp', '0003_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
