# Generated by Django 4.2.6 on 2023-10-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translateapp', '0004_alter_post_text_alter_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='card_status',
            field=models.CharField(blank=True, max_length=10, verbose_name='Card Status'),
        ),
    ]
