# Generated by Django 4.2.6 on 2023-10-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translateapp', '0006_remove_post_card_status_posttranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttranslation',
            name='description',
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
